//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pruebacrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla
    {
        public int id { get; set; }
        public string nombre_de_pelicula { get; set; }
        public string genero { get; set; }
        public System.DateTime fecha_compra { get; set; }
    }
}
